CREATE TABLE produtos (
    id                      BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                    TEXT NOT NULL,
    descricao               TEXT NOT NULL,
    setor                   TEXT CHECK (setor IN ('Higiene e Limpeza', 'Hortifruti', 'Açougue E Peixaria', 'Padaria e Confeitaria', 'Frios e Laticínios', 'Congelados', 'Bebidas', 'Mercearia'))  NOT NULL,
    preco                   NUMERIC NOT NULL,
    validade                DATE NOT NULL,
    imagem                  TEXT NOT NULL,
    peso                    TEXT NOT NULL,
    marca                   TEXT NOT NULL,
    quantidade_estoque      INTEGER NOT NULL,
    status_estoque          TEXT CHECK (status_estoque IN ('Disponível', 'Poucas unidades', 'Esgotado')) NOT NULL
);

CREATE TABLE usuarios (
    id               BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo    TEXT NOT NULL,
    email            TEXT NOT NULL UNIQUE,
    senha_hash       VARCHAR(255) NOT NULL,
    telefone         TEXT UNIQUE
);

CREATE TABLE funcionarios (
    id               BIGINT PRIMARY KEY,
    cargo            TEXT CHECK (cargo IN ('Operador de caixa', 'Empacotador', 'Repositor', 'Atendente de SAC',
                                            'Padeiro', 'Açougueiro', 'Estoquista', 'Motorista', 'Zelador',
                                            'Auxiliar administrativo', 'Gerente')),

    CONSTRAINT fk_funcionario_usuario FOREIGN KEY (id) REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE TABLE clientes (
    id               BIGINT PRIMARY KEY,
    endereco         TEXT,

    CONSTRAINT fk_cliente_usuario FOREIGN KEY (id) REFERENCES usuarios(id) ON DELETE CASCADE
);